mdapipkg/unpackaged/objects/A_R_info__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdjC_LocalSvc__c</fullName>
        <label>AdjC/LocalSvc</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Adjustments__c</fullName>
        <label>Adjustments</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_Cycle__c</fullName>
        <label>Bill Cycle</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Date__c</fullName>
        <label>Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Number__c</fullName>
        <label>Billing Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Seq_No__c</fullName>
        <label>Billing Sequence Number</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Pay_Date__c</fullName>
        <label>Last Pay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Library_id__c</fullName>
        <label>Library id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Bill__c</fullName>
        <label>Net Bill</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P_P_O_C_C__c</fullName>
        <label>P.P/O.C.C</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Prior_Bill__c</fullName>
        <label>Prior Bill</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seq_No__c</fullName>
        <label>Sequence Number</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toll_Charges__c</fullName>
        <label>Toll Charges</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Taxes__c</fullName>
        <label>Total Taxes</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>count__c</fullName>
        <formula>LEN( Account_Id__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>A/R Info</label>
    <nameField>
        <label>A/R info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A/R Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Adjustments__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Number__c</fullName>
        <label>Billing Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Billing_Seq_No__c</fullName>
        <label>Billing Sequence Number</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Library_Id__c</fullName>
        <label>Library Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Adjustments</label>
    <nameField>
        <label>Adjustments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/GAN__c.object
<CustomObject>
    <fields>
        <fullName>Library_id__c</fullName>
        <label>Library id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GAN</label>
    <nameField>
        <label>GAN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GANS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_id__c</fullName>
        <label>Account id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTN_Phone__c</fullName>
        <label>BTN Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CLLI__c</fullName>
        <label>CLLI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_Id__c</fullName>
        <label>Circuit Id</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_ID__c</fullName>
        <label>Company ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_name__c</fullName>
        <label>Company name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GAN__c</fullName>
        <label>GAN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Id__c</fullName>
        <label>Location Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <label>Service Location</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_Id__c</fullName>
        <label>Summary Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_master_phone__c</fullName>
        <label>Summary master phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>WTN_ID__c</fullName>
        <label>WTN ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WTN__c</fullName>
        <label>WTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>billing_id__c</fullName>
        <label>billing id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>hierarchy</label>
    <nameField>
        <label>hierarchy name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>hierarchys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/detailinfoController1.cls
public class detailinfoController1 {

    public LIST<hierarchy__c> Lsthier1 { get; set;}
    public static A_R_info__c objarinfo{get;set;}
    Public List<A_R_info__c> lstarinfo{get;set;}

        public detailinfoController1(){
 String strID = Apexpages.currentPage().getParameters().get('detailID');
        System.debug('**** strBTNValue ' + strID);
                      if(lsthier1.size()>0)

   // List<Hierarchy__c> lsthir = new List<hierarchy__c>();
     lsthier1 =[SELECT Account_id__c,billing_id__c,BTN_Phone__c,Circuit_Id__c,City__c,CLLI__c,Company_ID__c,Company_name__c,CreatedById,CreatedDate,GAN__c,Id,IsDeleted,LastModifiedById,LastModifiedDate,Level__c,Location_Id__c,Name,Name__c,OwnerId,Region__c,Service_Location__c,State__c,Summary_Id__c,Summary_master_phone__c,SystemModstamp,WTN_ID__c,WTN__c FROM hierarchy__c where id=:strID ];
              if(lstarinfo.size()>0){
            lstarinfo= [SELECT Account_Id__c,AdjC_LocalSvc__c,Adjustments__c,Balance__c,Billing_Number__c,Billing_Seq_No__c,Bill_Cycle__c,Bill_Date__c,count__c,CreatedById,CreatedDate,Id,IsDeleted,LastModifiedById,LastModifiedDate,Last_Pay_Date__c,Library_id__c,Name,Net_Bill__c,OwnerId,Payment__c,Phone_Number__c,Prior_Bill__c,P_P_O_C_C__c,Seq_No__c,SystemModstamp,Toll_Charges__c,Total_Taxes__c FROM A_R_info__c where Account_Id__c=:lsthier1[0].id];
}
        

}
   
      
}