mdapipkg/unpackaged/objects/A_R_info__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Date__c</fullName>
        <label>Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>A/R Info</label>
    <nameField>
        <label>A/R info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A/R Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Available_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Available Promotion</label>
    <nameField>
        <label>Available Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Available Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Credit_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Type_Of_Business__c</fullName>
        <label>Type Of Business</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Credit History</label>
    <nameField>
        <label>Credit History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Current_Pending_Promotions__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Current/Pending Promotions</label>
    <nameField>
        <label>Current/Available Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current/Pending Promotionss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Customer_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_ID__c</fullName>
        <label>Circuit ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Deposit_Refund__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Deposit/Refund</label>
    <nameField>
        <label>Deposit/Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposit/Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Dish_Transaction_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Dish Transaction History</label>
    <nameField>
        <label>Dish Transaction History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dish Transaction Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Handshake_transaction_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Handshake transaction History</label>
    <nameField>
        <label>Handshake transaction History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Handshake transaction Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_id__c</fullName>
        <label>Account id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTN_Phone__c</fullName>
        <label>BTN Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Circuit_Id__c</fullName>
        <label>Circuit Id</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WTN__c</fullName>
        <label>WTN</label>
        <type>Phone</type>
    </fields>
    <label>hierarchy</label>
    <nameField>
        <label>hierarchy name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>hierarchys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/ISP__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain_Name__c</fullName>
        <label>Domain Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>ISP</label>
    <nameField>
        <label>ISP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ISPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_Id__c</fullName>
        <label>Circuit Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Provisioning__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hunt_Group_Number__c</fullName>
        <label>Hunt Group Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Provisioning</label>
    <nameField>
        <label>Provisioning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisionings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Special_Access_Info__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIR_Number__c</fullName>
        <label>CIR Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Special Access Info</label>
    <nameField>
        <label>Special Access Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Access Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Toll__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Date__c</fullName>
        <label>Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Toll</label>
    <nameField>
        <label>Toll Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tolls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SummaryPageControllerTest.cls
@isTest
private class SummaryPageControllerTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Credit_History__c objCreditHistory = new Credit_History__c();
        objCreditHistory.Account_Id__c='76543278';
        objCreditHistory.Type_Of_Business__c='Resi';
        insert objCreditHistory;
       
        /*Provisioning__c objProvisioning = new Provisioning__c();
        objProvisioning.Account_Id__c='76543278';
        objProvisioning.Hunt_Group_Number__c='9213';
        insert objProvisioning;
        
        ISP__c objISP =new ISP__c();    
        objISP.Account_Id__c='76543278';
        objISP.Domain_Name__c='ghyr';
        insert objISP;
        
        Special_Access_Info__c objSpecialAccessInfo = new Special_Access_Info__c();
        objSpecialAccessInfo.Account_Id__c='76543278';
        objSpecialAccessInfo.CIR_Number__c=875.12;
        //objSpecialAccessInfo.OCC_CIR_Number__c=543.78;
        insert objSpecialAccessInfo;*/
        
        Customer_Account__c objCustomerAccount = new Customer_Account__c();
        objCustomerAccount.Account_Id__c='76543278';
        insert objCustomerAccount;
        
        hierarchy__c objHir = new hierarchy__c();
        objHir.BTN_Phone__c='123';
        objHir.Circuit_id__c='123';
        objHir.Account_Id__c='76543278';
        objHir.WTN__c ='1234567890';
        insert objHir;
        
        /*Product2 objProduct2 = new Product2();
        objProduct2.Name='TestProd';
        objProduct2.Account_Id__c='76543278';
        insert objProduct2;
        
        Available_Promotion__c objAvaPro = new Available_Promotion__c();
        objAvaPro.Account_Id__c='';
        objAvaPro.Name='AvenProd';
        insert objAvaPro;
        
        Current_Pending_Promotions__c objCurrPenPro = new Current_Pending_Promotions__c();
        objCurrPenPro.Name='currpend';
        objCurrPenPro.Account_Id__c='76543278';
        insert objCurrPenPro;
        
        Handshake_transaction_History__c objHanTrHis = new Handshake_transaction_History__c();
        objHanTrHis.Account_Id__c='76543278';
        objHanTrHis.Name='HanTrnHis';
        insert objHanTrHis;
        
        Dish_Transaction_History__c objDisTr = new Dish_Transaction_History__c();
        objDisTr.Name='distr';
        objDisTr.Account_Id__c='76543278';
        insert objDisTr;
        
        Equal_Access__c objEA = new Equal_Access__c();
        objEA.Name='eqacc';
        objEA.Account_Id__c='76543278';
        objEA.Seq__c='1';
        insert objEA;
        
        Deposit_Refund__c objDep = new Deposit_Refund__c();
        objDep.name='dep';
        objDep.Account_Id__c='76543278';
        objDep.Phone_Number__c='1234';
        insert objDep;
        
        Toll__c objToll = new Toll__c();
        objToll.Name='tool';
        objToll.Account_Id__c='76543278';
        insert objToll;*/
        
        A_R_info__c objAR = new A_R_info__c();
        objAR.Account_Id__c='76543278';
        objAR.Bill_Date__c=System.today();
        insert objAR;
        
        Apexpages.currentPage().getParameters().put('srcCriteria','Account');
        Apexpages.currentPage().getParameters().put('childValue','123');
        
        SummaryPageController objSummaryPage = new SummaryPageController();
        //objSummaryPage.objCustomerAccountInfo();
        SummaryPageController.objCustomerAccountInfo();
        
        //objSummaryPage.getDepositRefund();
        //Apexpages.currentPage().getParameters().put('selDepRefPhone',objDep.id);
        //objSummaryPage.getDepositRefund();
        
        //SummaryPageController.strAdjustmentTelephone='1234';
        //objSummaryPage.searchDepositInfoOnTelephone();
        
        //objSummaryPage.getTollDetails();
        //Apexpages.currentPage().getParameters().put('selToll',objToll.id);
        //objSummaryPage.getTollDetails();
        
        //objSummaryPage.searchTollOnTelephone();

        //SummaryPageController.strTNInformationTelephone='1234567890';
        //objSummaryPage.searchTNInfoOnTelephone();
        objSummaryPage.getData();
        SummaryPageController.getRemoteData();
        SummaryPageController.getChartData();
        objSummaryPage.getMonths();
        objSummaryPage.getYears();
        objSummaryPage.getSearchOnName('123');
        //objSummaryPage.ARInfoForSixMonths objAr = new objSummaryPage.ARInfoForSixMonths();
        objSummaryPage.getlstARInfoForSixMonths();
        objSummaryPage.prevSixMonths();
        
        
    }
}