mdapipkg/unpackaged/objects/Adventure__c.object
<CustomObject>
    <fields>
        <fullName>Difficult__c</fullName>
        <label>Difficulty Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One</fullName>
                </value>
                <value>
                    <fullName>Two</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Size__c</fullName>
        <label>Group Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length_d__c</fullName>
        <label>Length (d)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>180</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Group_Size__c</fullName>
        <label>Max Group Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Adventure</label>
    <nameField>
        <label>Adventure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Trip__c.object
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Trip_Leg__c.object
<CustomObject>
    <fields>
        <fullName>Adventure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adventure</label>
        <referenceTo>Adventure__c</referenceTo>
        <relationshipLabel>Trip Legs</relationshipLabel>
        <relationshipName>Trip_Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trip__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trip</label>
        <referenceTo>Trip__c</referenceTo>
        <relationshipLabel>Trip Legs</relationshipLabel>
        <relationshipName>Trip_Legs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Trip Leg</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Trip Leg AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trip Legs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TripControllerTest.cls
@isTest(SeeAllData=true)                    
private class TripControllerTest {
    public static testMethod void TripControllerMethodTest () { 
    
        Adventure__c adv=new Adventure__c();
        adv.name = 'test';
        adv.Group_Size__c = 10;
        adv.Length_d__c = 10;
        adv.Location__c = 'test';
        adv.Max_Group_Size__c = 10;
        adv.Difficult__c = 'One';
        insert adv;
        
        apexpages.currentpage().getparameters().put('id','');
        Trip__c TripObj=new Trip__c();
        ApexPages.StandardController stdCont=new ApexPages.StandardController(TripObj);
        TripController TripControllerObj=new TripController(stdCont);
        
        
        Trip__c tripdata=new Trip__c();
        tripdata.name = 'test';
        insert tripdata;
        Trip_Leg__c TripLeg = new Trip_Leg__c ();
        TripLeg.Trip__c =tripdata.id;
        insert TripLeg;
        
        apexpages.currentpage().getparameters().put('id',tripdata.id);
        ApexPages.StandardController stdCont1=new ApexPages.StandardController(tripdata);
        TripController TripControllerObj1=new TripController(stdCont1);
        
        List<SelectOption> lst= TripControllerObj1.getDiffValues();
       
        TripControllerObj1.pgSaveRecord();
        
        TripControllerObj1.strSelDiff='all';
        TripControllerObj1.forAdventrueRecrods();
        TripControllerObj1.strSelDiff='One';
        TripControllerObj1.forAdventrueRecrods();
        
        TripControllerObj1.Last();
        TripControllerObj1.Next();
        TripControllerObj1.Previous();
        TripControllerObj1.First();

    }
}