mdapipkg/unpackaged/objects/Answers__c.object
<CustomObject>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>project</label>
        <referenceTo>project__c</referenceTo>
        <relationshipLabel>answerss</relationshipLabel>
        <relationshipName>answerss</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answers</label>
    <nameField>
        <label>Answers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>answerss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/contract_names__c.object
<CustomObject>
    <fields>
        <fullName>Answers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answers</label>
        <referenceTo>Answers__c</referenceTo>
        <relationshipName>contract_namess</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendors__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendors</label>
        <referenceTo>Vendors__c</referenceTo>
        <relationshipLabel>contracts</relationshipLabel>
        <relationshipName>contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>contract</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>contract names</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/project__c.object
<CustomObject>
    <label>CNQuestions</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Vendors__c.object
<CustomObject>
    <label>Vendors</label>
    <nameField>
        <label>Vendors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/ClsSearchVendors.cls
public class ClsSearchVendors {
    public List<project__c> lstQuestion {get;set;}
    List<Answers__c> lstAnswers {get;set;}
    List<Vendors__c> lstVendors {get;set;}
    List<contract_names__c> lstContracts {get;set;}
    public List<SelectOption> options {get;set;}
    
    Map<id,project__c> MapObjQuestion {get;set;}
    Map<id,Answers__c> MapObjAnswers {get;set;}
    Map<id,Vendors__c> MapObjVendors {get;set;}
    Map<id,contract_names__c> MapObjContractNames {get;set;}
    
    public ClsSearchVendors(ApexPages.StandardController controller) {
         lstQuestion=new List<project__c>();
         lstQuestion = [SELECT Id,Name,OwnerId FROM project__c];
         options = new List<SelectOption>();
         
         for(project__c objQesTemp:lstQuestion ){
            options.add(new SelectOption('SAM','Sam I Am'));
    
         }
         
    }


  /* ClsSearchVendors(){

        lstQuestion = [SELECT Id,Name,OwnerId FROM project__c];
    }*/
    
    public PageReference pageRedirect() {
        return null;
    }

}