mdapipkg/unpackaged/objects/Billing_Detail_2__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_E_To_Date__c</fullName>
        <label>S&amp;E To Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Detail 2</label>
    <nameField>
        <label>Billing Detail 2  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Detail 2&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/DeleteProcessedDataTest.cls
@isTest 
private class DeleteProcessedDataTest {
    static testMethod void validateDelProcess() {
        Billing_Detail_2__c objBD = new Billing_Detail_2__c();
        objBD.Account_Id__c  = '12345';
        objBD.S_E_To_Date__c = System.today();
        insert objBD;
        
        Billing_Detail_2__c objBD1 = new Billing_Detail_2__c();
        objBD1.Account_Id__c  = '12345';
        objBD1.S_E_To_Date__c = System.today()+1;
        insert objBD1;
    }
}