mdapipkg/unpackaged/objects/custom__c.object
<CustomObject>
    <fields>
        <fullName>DivisionHide__c</fullName>
        <label>DivisionHide</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>DivisionHide__c</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>author__c</fullName>
        <label>author</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>bruce</fullName>
                    <default>true</default>
                    <label>bruce</label>
                </value>
                <value>
                    <fullName>micheal</fullName>
                </value>
                <value>
                    <fullName>paul</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>general</fullName>
                    <default>true</default>
                    <label>general</label>
                </value>
                <value>
                    <fullName>issues</fullName>
                </value>
                <value>
                    <fullName>stakeholders</fullName>
                </value>
                <value>
                    <fullName>events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>custom</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>WAR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>customs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/userdivision__c.object
<CustomObject>
    <fields>
        <fullName>division__c</fullName>
        <label>division</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>userdivisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>userdivision</label>
    <nameField>
        <label>userfield Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>userdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClsAddReport.cls
public class ClsAddReport {
    public String strAuthor{get;set;}
    public String strDivision{get;set;}
    public custom__c cusRecord;
    public boolean bolShowExisRecod{get;set;}
    public boolean bolSave{get;set;}
    
    public ClsAddReport(ApexPages.StandardController controller) {
        strAuthor = UserInfo.getName();    //Get Uthoer Name
        userdivision__c ObjDiv = [Select u.username__c, u.division__c From userdivision__c u where u.username__c=:UserInfo.getUserId()];
        strDivision=ObjDiv.division__c;
        bolShowExisRecod = true; //Display existing Records
    }
    
    //This will save the record
    public PageReference saveRecord(){
       
        insert cusRecord;    //Insert a new record
        
        bolShowExisRecod = true;
        bolSave = false;
        
        return null;
    }
    
    //This will open a new window to record
    public PageReference NewRecord(){
       bolShowExisRecod = false;
       bolSave = true;
        
        return null;
    }
    //Cancels the window
    public PageReference cancel(){
      bolShowExisRecod = true;
        bolSave = false;
        
        return null;
    }
    public custom__c getCustomRecod(){
        if(cusRecord==null)
            cusRecord = new custom__c();
       
        cusRecord.date__c = System.today();
        return cusRecord;
    }
    
    public List<custom__c> getAllRecord(){
        return [Select c.Notes__c, c.date__c, c.category__c, c.author__c, c.Name, c.Division__c, c.DivisionHide__c, c.CreatedDate From custom__c c where c.OwnerId=:UserInfo.getUserId()];
    }

}