mdapipkg/unpackaged/objects/custom__c.object
<CustomObject>
    <fields>
        <fullName>DivisionHide__c</fullName>
        <label>DivisionHide</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>DivisionHide__c</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>author__c</fullName>
        <label>author</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>bruce</fullName>
                    <default>true</default>
                    <label>bruce</label>
                </value>
                <value>
                    <fullName>micheal</fullName>
                </value>
                <value>
                    <fullName>paul</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>general</fullName>
                    <default>true</default>
                    <label>general</label>
                </value>
                <value>
                    <fullName>issues</fullName>
                </value>
                <value>
                    <fullName>stakeholders</fullName>
                </value>
                <value>
                    <fullName>events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>custom</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>WAR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>customs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/userdivision__c.object
<CustomObject>
    <fields>
        <fullName>division__c</fullName>
        <label>division</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>userdivisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>userdivision</label>
    <nameField>
        <label>userfield Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>userdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/ClsCustomTest.cls
@isTest
private class ClsCustomTest {

    static testMethod void myUnitTest() {
        test.startTest();
       //Insert data
        User tempuser;
       
    	Profile PInstal = [select id from Profile where name = 'System Administrator'];
    	tempuser = new User(profileid=PInstal.Id,alias = 'standt', email='standarduser00735@accenture.com',
                    emailencodingkey='UTF-8', lastname='Tsting15', languagelocalekey='en_US',
                    localesidkey='en_US',timezonesidkey='America/Los_Angeles', username='standardser007@accenture.com'
                    );
        insert tempuser;
        
        userdivision__c objDiv = new userdivision__c();
        objDiv.username__c = tempuser.id;
        objDiv.division__c = '-- Select One --';
        insert objDiv;
        
        custom__c csReprot = new custom__c();
        csReprot.Notes__c = 'test notes';
        csReprot.author__c = 'author';
        csReprot.category__c ='category';
        //csReprot.Division__c(1);
        //csReprot.Name ='name';
        insert csReprot;
        
       

        // [Select c.Notes__c, c.date__c, c.category__c, c.author__c, c.Name, c.Division__c, c.DivisionHide__c, c.CreatedDate From custom__c c where c.OwnerId=:UserInfo.getUserId()];
    
        ClsCustom clsRUM = new ClsCustom(new ApexPages.StandardController(csReprot));
        
        
        
        clsrum.getCusList();
        //clsrum.custom();
       // clsrum.customResult();
        clsrum.getFromDate();
        clsrum.getToDate();
        clsrum.download();
        clsrum.editVal();
        clsrum.getAuthor();
        clsrum.getCategory();
        clsrum.getDivision();
        clsrum.msgBolVal();
        //Set author and category vaue
        clsrum.authorVal = 'author';
        clsRUM.categoryVal='category';
        clsrum.strKeySearch = 'ha';
        clsrum.strDivOnReport ='test report';
        clsrum.fromDate.date__c  = system.today()+300;
        clsrum.toDate.date__c = system.today();
        clsrum.getCusList();
        
        clsrum.authorVal = '-- Select One --';
        clsRUM.categoryVal='-- Select One --';
        clsrum.bolShowDivision = false;
        clsrum.fromDate.date__c  = system.today()-300;
        clsrum.toDate.date__c = system.today();
        clsrum.getCusList();
        
        clsrum.divisionVal = '-- Select One --';
        //clsrum.strLikeString ='this';
        clsrum.authorVal='-- Select One --';
        clsRUM.categoryVal='-- Select One --';
        clsrum.divisionVal = '-- Select One --';
        clsrum.bolShowDivision = true;
        clsrum.bolDisplaySaveButt = false;
        clsrum.fromDate.date__c  = system.today()-300;
        clsrum.toDate.date__c = system.today();
         System.debug('**** divisionVal ' + clsrum.divisionVal + '    ' + clsrum.bolShowDivision );
        clsrum.getCusList();
         System.debug('**** authorVal1 ' + clsrum.authorVal + '    ' + clsrum.categoryVal );
      //  clsrum.lstFinalOut();
        
        clsrum.divisionVal = '-- Select One --';
        clsrum.authorVal='-- Select One --';
        clsRUM.categoryVal='-- sSelect One --';
        clsrum.divisionVal = '-- Select One --';
        clsrum.bolShowDivision = true;
        clsrum.bolDisplaySaveButt = false;
        clsrum.fromDate.date__c  = system.today()-300;
        clsrum.toDate.date__c = system.today();
         System.debug('**** divisionVal ' + clsrum.divisionVal + '    ' + clsrum.bolShowDivision );
        clsrum.getCusList();
        
        clsrum.divisionVal = '-- Select One --';
        clsrum.authorVal='-- sSelect One --';
        clsRUM.categoryVal='-- Select One --';
        clsrum.divisionVal = '-- Select One --';
        clsrum.bolShowDivision = true;
        clsrum.bolDisplaySaveButt = false;
        clsrum.fromDate.date__c  = system.today()-300;
        clsrum.toDate.date__c = system.today();
         System.debug('**** divisionVal ' + clsrum.divisionVal + '    ' + clsrum.bolShowDivision );
        clsrum.getCusList();
        
        clsrum.save();
        
        test.stopTest();
    }
}