mdapipkg/unpackaged/objects/Directory__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_Line__c</fullName>
        <label>Description Line</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Code_1__c</fullName>
        <label>Directory Code 1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Code_2__c</fullName>
        <label>Directory Code 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Code_3__c</fullName>
        <label>Directory Code 3</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Code_4__c</fullName>
        <label>Directory Code 4</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Code_5__c</fullName>
        <label>Directory Code 5</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Listing_Code__c</fullName>
        <label>Directory Listing Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Mailing_Address__c</fullName>
        <label>Directory Mailing Address</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Sequence_Number__c</fullName>
        <label>Last Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Library_id__c</fullName>
        <label>Library id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_number__c</fullName>
        <label>Line number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>List_With_Phone_Number__c</fullName>
        <label>List With Phone Number</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing_Sequence__c</fullName>
        <label>Listing Sequence</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <label>Reference Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Directory</label>
    <nameField>
        <label>Directory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Directorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Order_Number__c.object
<CustomObject>
    <label>Service Order</label>
    <nameField>
        <label>Order Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Products__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active_Flag_A__c</fullName>
        <label>Active Flag A</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bundle_Name__c</fullName>
        <label>Bundle Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Code__c</fullName>
        <label>Charge Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Rate__c</fullName>
        <label>Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Circuit_Id__c</fullName>
        <label>Circuit Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connect_Date__c</fullName>
        <label>Connect Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cust_Owned_Maint_Equipment__c</fullName>
        <label>Cust Owned/Maint Equipment</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DC__c</fullName>
        <label>DC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disconnect_Date__c</fullName>
        <label>Disconnect Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generic_SKU__c</fullName>
        <label>Generic SKU</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grouping_Name__c</fullName>
        <label>Grouping Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ICB_Code_Flag__c</fullName>
        <label>ICB Code/Flag</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IN_Service_Order__c</fullName>
        <label>IN Service Order</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>I_HSI_WIFI__c</fullName>
        <label>I(HSI/WIFI)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InDATE__c</fullName>
        <label>InDATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <label>Item Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Sequence_Number__c</fullName>
        <label>Item Sequence Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Library_id__c</fullName>
        <label>Library id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRC_NRC_FLag__c</fullName>
        <label>MRC/NRC FLag</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NO_Flag_Tax_T__c</fullName>
        <label>NO Flag Tax(T)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Reaccuring_Charges__c</fullName>
        <label>Non Reaccuring Charges</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OUT_Service_Order__c</fullName>
        <label>OUT Service Order</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Out_Date__c</fullName>
        <label>Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Description__c</fullName>
        <label>Package Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Prefix_P__c</fullName>
        <label>Prefix(P)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroupingSequence__c</fullName>
        <label>ProductGroupingSequence</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_GroupId__c</fullName>
        <label>Product GroupId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Rate__c</fullName>
        <label>Product Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reacuuring_Charges__c</fullName>
        <label>Reacuuring Charges</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_E_Type_Flag__c</fullName>
        <label>S&amp;E Type Flag</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_E__c</fullName>
        <label>S&amp;E</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <label>Service Location</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Type_ST__c</fullName>
        <label>Service Type(ST)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_S__c</fullName>
        <label>Status(S)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vacation_Reactivation_Date__c</fullName>
        <label>Vacation Reactivation Date</label>
        <type>Date</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CombineTableController.cls
public class CombineTableController {
    
    public List<Products__c> lstProducts    {get;set;}
    public List<Directory__c> lstDirectory    {get;set;}
    public boolean displayPopup {get; set;} 
    
    public CombineTableController(){
        //String strAccountID=apexpages.currentpage().getparameters().get('accID');
        
        //lstProducts = [SELECT Account_Id__c,Active_Flag_A__c,Bundle_Name__c,Charge_Code__c,Charge_Rate__c,Circuit_Id__c,Connect_Date__c,CreatedById,CreatedDate,Cust_Owned_Maint_Equipment__c,DC__c,Description__c,Disconnect_Date__c,Generic_SKU__c,Grouping_Name__c,ICB_Code_Flag__c,Id,InDATE__c,IN_Service_Order__c,IsDeleted,Item_Number__c,Item_Sequence_Number__c,I_HSI_WIFI__c,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Library_id__c,MRC_NRC_FLag__c,Name,Non_Reaccuring_Charges__c,NO_Flag_Tax_T__c,Order_Number__c,Out_Date__c,OUT_Service_Order__c,OwnerId,Package_Code__c,Package_Description__c,Package_Name__c,Phone_Number__c,Prefix_P__c,ProductGroupingSequence__c,Product_GroupId__c,Product_Group__c,Product_Rate__c,Quantity__c,Reacuuring_Charges__c,Sequence_Number__c,Sequence__c,Service_Location__c,Service_Type_ST__c,Service_Type__c,Status_S__c,SystemModstamp,S_E_Type_Flag__c,S_E__c,Vacation_Reactivation_Date__c FROM Products__c limit 1000];
        //lstDirectory = [SELECT Account_Id__c,CreatedById,CreatedDate,Description_Line__c,Description__c,Directory_Code_1__c,Directory_Code_2__c,Directory_Code_3__c,Directory_Code_4__c,Directory_Code_5__c,Directory_Listing_Code__c,Directory_Mailing_Address__c,Id,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Last_Sequence_Number__c,Library_id__c,Line_number__c,Listing_Sequence__c,List_With_Phone_Number__c,Name,OwnerId,Phone_Number__c,Reference_Number__c,Sequence_Number__c,SystemModstamp FROM Directory__c limit 1000];
    }
    
        
    
    public void closePopup() {        
        displayPopup = false;    
    }     
    public void showPopup() {        
        displayPopup = true;  
        
        String strAccountID=apexpages.currentpage().getparameters().get('accID');
        
        lstProducts = [SELECT Account_Id__c,Active_Flag_A__c,Bundle_Name__c,Charge_Code__c,Charge_Rate__c,Circuit_Id__c,Connect_Date__c,CreatedById,
                    CreatedDate,Cust_Owned_Maint_Equipment__c,DC__c,Description__c,Disconnect_Date__c,Generic_SKU__c,Grouping_Name__c,ICB_Code_Flag__c,
                    Id,InDATE__c,IN_Service_Order__c,IsDeleted,Item_Number__c,Item_Sequence_Number__c,I_HSI_WIFI__c,LastModifiedById,LastModifiedDate,
                    LastReferencedDate,LastViewedDate,Library_id__c,MRC_NRC_FLag__c,Name,Non_Reaccuring_Charges__c,NO_Flag_Tax_T__c,Order_Number__c,
                    Out_Date__c,OUT_Service_Order__c,OwnerId,Package_Code__c,Package_Description__c,Package_Name__c,Phone_Number__c,Prefix_P__c,
                    ProductGroupingSequence__c,Product_GroupId__c,Product_Group__c,Product_Rate__c,Quantity__c,Reacuuring_Charges__c,
                    Sequence_Number__c,Sequence__c,Service_Location__c,Service_Type_ST__c,Service_Type__c,Status_S__c,SystemModstamp,S_E_Type_Flag__c,
                    S_E__c,Vacation_Reactivation_Date__c FROM Products__c WHERE Account_Id__c=:strAccountID limit 1000];
                    
        lstDirectory = [SELECT Account_Id__c,CreatedById,CreatedDate,Description_Line__c,Description__c,Directory_Code_1__c,Directory_Code_2__c,
                    Directory_Code_3__c,Directory_Code_4__c,Directory_Code_5__c,Directory_Listing_Code__c,Directory_Mailing_Address__c,Id,IsDeleted,
                    LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Last_Sequence_Number__c,Library_id__c,Line_number__c,
                    Listing_Sequence__c,List_With_Phone_Number__c,Name,OwnerId,Phone_Number__c,Reference_Number__c,Sequence_Number__c,SystemModstamp 
                    FROM Directory__c WHERE Account_Id__c=:strAccountID limit 1000];
      
    }
    
}