mdapipkg/unpackaged/objects/hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_id__c</fullName>
        <label>Account id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTN_Phone__c</fullName>
        <label>BTN Phone</label>
        <type>Phone</type>
    </fields>
    <label>hierarchy</label>
    <nameField>
        <label>hierarchy name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>hierarchys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/buttoncontTest.cls
@isTest
private class buttoncontTest{

    static testMethod void myUnitTest() {
        hierarchy__c objhir = new hierarchy__c();
        objhir.Account_id__c='Test';
        objhir.BTN_Phone__c='1234567890';
        insert objhir;
         Test.startTest();
           Test.setCurrentPage(page.button);
           Apexpages.currentPage().getParameters().put('btnNum','1234567890');
           Test.stopTest();
    }
}