mdapipkg/unpackaged/objects/hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>BTN_Phone__c</fullName>
        <label>BTN Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billing_id__c</fullName>
        <label>billing id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>hierarchy</label>
    <nameField>
        <label>hierarchy name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>hierarchys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/detailinfoController.cls
public class detailinfoController {

    public String getLsthier1() {
        return null;
    }


    public List<hierarchy__c> Lsthier{ get; set;}
   

 public List<search2> lstDetails    {get;set;}
    
    public detailinfoController(){
        //REad the BTN VAlue
        String strID = Apexpages.currentPage().getParameters().get('detailID');
        System.debug('**** strBTNValue ' + strID);
    List<hierarchy__c> Lsthier = [Select Name__c, Id,BTN_Phone__c,billing_id__c from hierarchy__c Where Id=:strID];
}


   
}