mdapipkg/unpackaged/objects/hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>BTN_Phone__c</fullName>
        <label>BTN Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>hierarchy</label>
    <nameField>
        <label>hierarchy name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>hierarchys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/mysearchcls.cls
public class mysearchcls {
public List<hierarchy__c> lsthir { get; set; }
public String strINputVal    {get;set;}

public PageReference search() {
        String strQuery = 'Select Name__c, BTN_Phone__c from hierarchy__c where Name__c LIKE \'%' + strINputVal + '%\'';
        //lsthir = [Select Name__c, BTN_Phone__c from hierarchy__c where Name__c=:strINputVal];
        lsthir = Database.query(strQuery);
        return null;
    }

}