mdapipkg/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CPE_NRC_Price_c__c</fullName>
        <label>CPE_NRC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NRC_Price_c__c</fullName>
        <label>NRC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OppLI__c</fullName>
        <formula>PricebookEntry.Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OppLI</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quooo__c</fullName>
        <label>Quooo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_MRC__c</fullName>
        <label>Renewal MRC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_months__c</fullName>
        <label>Term(Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lineItem__c</fullName>
        <formula>PricebookEntry.Product2.Item_Code__c</formula>
        <label>lineItem</label>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/classes/ForAttachementExampleContr.cls
public class ForAttachementExampleContr {

    public PageReference saveFileToOpp() {
        Attachment att = new Attachment(name ='Invoice_AnyUniqueName.pdf');
         PageReference invoicePage = Page.OppProductPDF;
         invoicePage .getParameters().put('id',apexpages.currentpage().getparameters().get('id'));
         // return page content as blob type
         // Alt: att.body = invoicePage .getContentAsPDF();
         att.body = invoicePage .getContent();
         // Associate with project's record Id
         att.parentid = apexpages.currentpage().getparameters().get('id');
         insert att;
        return null;
    }

    public List<OpportunityLineItem> lstOppLinITem    {get;set;}
    public ForAttachementExampleContr(){
        lstOppLinITem = [SELECT CPE_NRC_Price_c__c,lineItem__c,ListPrice,NRC_Price_c__c,OppLI__c,OpportunityId,PricebookEntryId,Quantity,Quooo__c,Renewal_MRC__c,Term_months__c,TotalPrice,UnitPrice FROM OpportunityLineItem WHERE OpportunityId =:apexpages.currentpage().getparameters().get('id')];
    }
}