mdapipkg/unpackaged/objects/SterlingQuote__c.object
<CustomObject>
    <fields>
        <fullName>CreatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SterlingQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LastModifiedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SterlingQuotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <label>SterlingQuote</label>
    <nameField>
        <label>SterlingQuote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SterlingQuotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/SterlingQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>AddressDescription__c</fullName>
        <label>AddressDescription</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressText__c</fullName>
        <description>AddressText</description>
        <label>AddressText</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AddressType__c</fullName>
        <label>AddressType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ServiceAddress</fullName>
                </value>
                <value>
                    <fullName>PostalAddress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AdjustedMRC__c</fullName>
        <label>AdjustedMRC</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AdjustedNRC__c</fullName>
        <label>AdjustedNRC</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BuildingName__c</fullName>
        <label>BuildingName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingNumber__c</fullName>
        <label>BuildingNumber</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingSubNumber__c</fullName>
        <label>BuildingSubNumber</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQLineNumber__c</fullName>
        <label>CPQLineNumber</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SterlingQuoteItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DataRegion__c</fullName>
        <label>DataRegion</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DiscountType__c</fullName>
        <label>DiscountType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>SVP</fullName>
                </value>
                <value>
                    <fullName>RSM</fullName>
                </value>
                <value>
                    <fullName>ICB</fullName>
                </value>
                <value>
                    <fullName>INA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount_DiscountAmountDiscountAmount__c</fullName>
        <label>Discount_DiscountAmount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GFItem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GFItem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsAddressQualified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAddressQualified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsContracted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsContracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsNewConstruction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsNewConstruction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPromoProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPromoProduct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTerm__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsTerm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsZAddressRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsZAddressRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ItemCode__c</fullName>
        <label>ItemCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastModifiedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SterlingQuoteItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LineNumber__c</fullName>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Locality__c</fullName>
        <label>Locality</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetroEQualificationType__c</fullName>
        <label>MetroEQualificationType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Match</fullName>
                </value>
                <value>
                    <fullName>Terminal Match</fullName>
                </value>
                <value>
                    <fullName>Exchange Match</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NPA__c</fullName>
        <label>NPA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NXX__c</fullName>
        <label>NXX</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NetworkDistance__c</fullName>
        <label>NetworkDistance</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumInstallments__c</fullName>
        <label>NumInstallments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSKU__c</fullName>
        <label>PSKU</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PercentageDiscountAmount__c</fullName>
        <label>PercentageDiscountAmount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SterlingQuoteItems</relationshipLabel>
        <relationshipName>SterlingQuoteItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>Product Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProductInterval__c</fullName>
        <label>ProductInterval</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PromoDiscountAmount__c</fullName>
        <label>PromoDiscountAmount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PromoExpirationDate__c</fullName>
        <label>PromoExpirationDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PromoName__c</fullName>
        <label>PromoName</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PromotionId__c</fullName>
        <label>PromotionId</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestedDueDate__c</fullName>
        <label>RequestedDueDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduleId__c</fullName>
        <label>ScheduleId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceControlNumber__c</fullName>
        <label>ServiceControlNumber</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceDate__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceSequenceNumber__c</fullName>
        <label>ServiceSequenceNumber</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StandardMRC__c</fullName>
        <label>StandardMRC</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StandardNRC__c</fullName>
        <label>StandardNRC</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StateOrProvince__c</fullName>
        <label>StateOrProvince</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <label>SterlingQuoteItem</label>
    <nameField>
        <label>SterlingQuoteItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SterlingQuoteItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/StearlingQuoteItemViewController.cls
public class StearlingQuoteItemViewController {
    public SterlingQuoteItem__c objSQi    {get;set;}
    
    public StearlingQuoteItemViewController(ApexPages.StandardController controller) {
        objSQi = [SELECT AddressDescription__c,AddressText__c,AddressType__c,AdjustedMRC__c,AdjustedNRC__c,BuildingName__c,BuildingNumber__c,BuildingSubNumber__c,
            CPQLineNumber__c,CreatedById,CreatedBy__c,CreatedDate,DataRegion__c,Description__c,DiscountType__c,Discount_DiscountAmountDiscountAmount__c,
            GFItem__c,Id,IsAddressQualified__c,IsContracted__c,IsDeleted,IsNewConstruction__c,IsPromoProduct__c,IsTerm__c,IsZAddressRequired__c,ItemCode__c,
            LastModifiedBy__c,LastModifiedDate,LastReferencedDate,LastViewedDate,LineNumber__c,ListPrice__c,Locality__c,MetroEQualificationType__c,Name,
            NetworkDistance__c,NPA__c,NumInstallments__c,NXX__c,PercentageDiscountAmount__c,Postcode__c,Product2__c,ProductCode__c,ProductInterval__c,
            PromoDiscountAmount__c,PromoExpirationDate__c,PromoName__c,PromotionId__c,PSKU__c,Quantity__c,RequestedDueDate__c,ScheduleId__c,
            ServiceControlNumber__c,ServiceDate__c,ServiceSequenceNumber__c,SKU__c,StandardMRC__c,StandardNRC__c,StateOrProvince__c,Status_Date__c,Status__c,
            SterlingQuote__c,StreetDirection__c,StreetName__c,StreetNrFirst__c,StreetSubDescription__c,StreetSuffix__c,Subdivision__c,Subtotal__c,
            TermEndDateMismatch__c,TermEndDate__c,TermLength__c,TotalPrice__c,UnitPrice__c,unit_Designator__c,unit_number__c,WireCenter__c 
            FROM SterlingQuoteItem__c where id=:apexpages.currentpage().getparameters().get('id')];
    }

    
    public StearlingQuoteItemViewController (){
            /*objSQi = [SELECT AddressDescription__c,AddressText__c,AddressType__c,AdjustedMRC__c,AdjustedNRC__c,BuildingName__c,BuildingNumber__c,BuildingSubNumber__c,
            CPQLineNumber__c,CreatedById,CreatedBy__c,CreatedDate,DataRegion__c,Description__c,DiscountType__c,Discount_DiscountAmountDiscountAmount__c,
            GFItem__c,Id,IsAddressQualified__c,IsContracted__c,IsDeleted,IsNewConstruction__c,IsPromoProduct__c,IsTerm__c,IsZAddressRequired__c,ItemCode__c,
            LastModifiedBy__c,LastModifiedDate,LastReferencedDate,LastViewedDate,LineNumber__c,ListPrice__c,Locality__c,MetroEQualificationType__c,Name,
            NetworkDistance__c,NPA__c,NumInstallments__c,NXX__c,PercentageDiscountAmount__c,Postcode__c,Product2__c,ProductCode__c,ProductInterval__c,
            PromoDiscountAmount__c,PromoExpirationDate__c,PromoName__c,PromotionId__c,PSKU__c,Quantity__c,RequestedDueDate__c,ScheduleId__c,
            ServiceControlNumber__c,ServiceDate__c,ServiceSequenceNumber__c,SKU__c,StandardMRC__c,StandardNRC__c,StateOrProvince__c,Status_Date__c,Status__c,
            SterlingQuote__c,StreetDirection__c,StreetName__c,StreetNrFirst__c,StreetSubDescription__c,StreetSuffix__c,Subdivision__c,Subtotal__c,
            TermEndDateMismatch__c,TermEndDate__c,TermLength__c,TotalPrice__c,UnitPrice__c,unit_Designator__c,unit_number__c,WireCenter__c 
            FROM SterlingQuoteItem__c where id=:apexpages.currentpage().getparameters().get('id')];*/
    }
}