mdapipkg/unpackaged/objects/SterlingQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>AddressText__c</fullName>
        <description>AddressText</description>
        <label>AddressText</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AddressType__c</fullName>
        <label>AddressType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ServiceAddress</fullName>
                </value>
                <value>
                    <fullName>PostalAddress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BuildingName__c</fullName>
        <label>BuildingName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingNumber__c</fullName>
        <label>BuildingNumber</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingSubNumber__c</fullName>
        <label>BuildingSubNumber</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locality__c</fullName>
        <label>Locality</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPA__c</fullName>
        <label>NPA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NXX__c</fullName>
        <label>NXX</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceControlNumber__c</fullName>
        <label>ServiceControlNumber</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceSequenceNumber__c</fullName>
        <label>ServiceSequenceNumber</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateOrProvince__c</fullName>
        <label>StateOrProvince</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetDirection__c</fullName>
        <label>StreetDirection</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetName__c</fullName>
        <label>StreetName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetNrFirst__c</fullName>
        <label>StreetNrFirst</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetSubDescription__c</fullName>
        <label>StreetSubDescription</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetSuffix__c</fullName>
        <label>StreetSuffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WireCenter__c</fullName>
        <label>WireCenter</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unit_Designator__c</fullName>
        <label>unit Designator</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unit_number__c</fullName>
        <label>unit number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>SterlingQuoteItem</label>
    <nameField>
        <label>SterlingQuoteItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SterlingQuoteItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/ZAddress__c.object
<CustomObject>
    <description>Contains all Z Addresses for Quote</description>
    <fields>
        <fullName>AddressText__c</fullName>
        <label>AddressText</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AddressType__c</fullName>
        <label>AddressType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ServiceAddress</fullName>
                </value>
                <value>
                    <fullName>PostalAddress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BuildingName__c</fullName>
        <label>BuildingName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingNumber__c</fullName>
        <label>BuildingNumber</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingSubNumber__c</fullName>
        <label>BuildingSubNumber</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsInFrontierFootprint__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsInFrontierFootprint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locality__c</fullName>
        <label>Locality</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPA__c</fullName>
        <label>NPA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NXX__c</fullName>
        <label>NXX</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Item_Number__c</fullName>
        <label>Quote Line Item Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Zaddresss</relationshipLabel>
        <relationshipName>Zaddresss</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceControlNumber__c</fullName>
        <label>ServiceControlNumber</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceSequenceNumber__c</fullName>
        <label>ServiceSequenceNumber</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateOrProvince__c</fullName>
        <label>StateOrProvince</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SterlingQuoteItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SterlingQuoteItem</label>
        <referenceTo>SterlingQuoteItem__c</referenceTo>
        <relationshipLabel>Zaddresss</relationshipLabel>
        <relationshipName>Zaddresss</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetDirection__c</fullName>
        <label>StreetDirection</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetName__c</fullName>
        <label>StreetName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetNrFirst__c</fullName>
        <label>StreetNrFirst</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetSubDescription__c</fullName>
        <label>StreetSubDescription</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetSuffix__c</fullName>
        <label>StreetSuffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WireCenter__c</fullName>
        <label>WireCenter</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Z_Service_Address__c</fullName>
        <label>Z Service Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>unit_Designator__c</fullName>
        <label>unit Designator</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unit_number__c</fullName>
        <label>unit number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ZAddress</label>
    <nameField>
        <displayFormat>ZA-{00000000}</displayFormat>
        <label>ZAddress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zaddresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/zaddressRadioCtrl.cls
public class zaddressRadioCtrl {
    public String strID {get;set;}
    public String strPopMsg    {get;set;}
    public List<zAddSub> lstDisList    {get;set;}
    public List<zAddSub> lstSelRec    {get;set;}
    public String strURL    {get;set;}
    public String strSelID    {get;set;}
    
    public zaddressRadioCtrl(ApexPages.StandardController controller) {
        strID = apexpages.currentpage().getparameters().get('qli');
        strURL='test';
        lstDisList =  new List<zAddSub>();
        lstSelRec  =  new List<zAddSub>();
        //Get list of ZAddressses
        List<ZAddress__c> lstA = [SELECT AddressText__c,AddressType__c,BuildingName__c,BuildingNumber__c,BuildingSubNumber__c,Country__c,CreatedById,CreatedDate,Id,IsDeleted,IsInFrontierFootprint__c,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Locality__c,Name,NPA__c,NXX__c,OwnerId,Postcode__c,Quote_Line_Item_Number__c,Quote_Line_Number__c,ServiceControlNumber__c,ServiceSequenceNumber__c,StateOrProvince__c,SterlingQuoteItem__c,StreetDirection__c,StreetName__c,StreetNrFirst__c,StreetSubDescription__c,StreetSuffix__c,Subdivision__c,SystemModstamp,unit_Designator__c,unit_number__c,WireCenter__c,Z_Service_Address__c FROM ZAddress__c WHERE SterlingQuoteItem__c=:strID ];
        for(ZAddress__c objz:lstA ){
            zAddSub objza = new zAddSub();
            objza.bolSelected = false;
            objza.objZAdd= objZ;
            objza.strID = objZ.id;
            lstDisList.add(objza);
        }
        
    }
    //public void showPopup(){
    
    //}
    public class zAddSub{
        public Boolean bolSelected    {get;set;}
        public String strID    {get;set;}
        public ZAddress__c objZAdd {get;set;}
    }
    
    public boolean displayPopup {get; set;}     
    public pageReference  closePopup() {        
        displayPopup = false;   
        
        //Save Record to DB
        ZAddress__c objZ = new ZAddress__c(id=lstSelRec[0].objZAdd.id);
        objZ.BuildingName__c = strPopMsg;
        upsert objZ;
        
        //String concate the given values
   /*     String strURL = 'https://c.na12.visual.force.com/alocNpanxx='+ objZ.name +'&alocStreet='+ objZ.BuildingNumber__c;
        pageReference pg = new pageReference(strURL);
        pg.setRedirect(true);
        return pg; */
        return null;
         
    }     
    public pageReference showPopup() {
         lstSelRec.clear();
         
          for(zAddSub objzs : lstDisList){
                if(objzs.bolSelected==true){
                    lstSelRec.add(objzs);
                }
            }
        //strSelID = apexpages.currentpage().getparameters().get('tt');
        System.debug('**** lstSelRec ' +lstSelRec + '    ' + lstSelRec.size() + '     strSelID  ' + strSelID );
        
       /* if(lstSelRec.size()==0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Please Select only one address'));
            return null;
        }
         
         displayPopup = true; 
           
         ZAddress__c objZ = new ZAddress__c(id=lstSelRec[0].objZAdd.id);
         strURL = 'https://c.na12.visual.force.com/alocNpanxx='+ objZ.name +'&alocStreet='+ objZ.BuildingNumber__c;
         System.debug('**** strURL  ' +strURL );
        
        pageReference pg = new pageReference(strURL);
         pg.setRedirect(true);*/
        //return pg; 
       return null;
      
        
    /*    if(lstSelRec.size()>1){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Please Select only one address'));
            return null;
        }
         */
      //  displayPopup = true;    
      //  return null;
    }
    public String getURLVal(){
        System.debug('**** strURL 1 ' +strURL );
        return strURL;
    }
}