mdapipkg/unpackaged/objects/Testing__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OS_Type__c</fullName>
        <label>computer parts</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Windows</fullName>
                </value>
                <value>
                    <fullName>IOS</fullName>
                </value>
                <value>
                    <fullName>LINUX</fullName>
                </value>
                <value>
                    <fullName>apple mouse</fullName>
                </value>
                <value>
                    <fullName>windows harddisk</fullName>
                </value>
                <value>
                    <fullName>apple mointors</fullName>
                </value>
                <value>
                    <fullName>apple headset</fullName>
                </value>
                <value>
                    <fullName>windows keyboard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Testing</label>
    <nameField>
        <label>Testing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Testings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Testingtrigger_handler.cls
public class Testingtrigger_handler
{ // helper or handler
    
    public static void beforeinsertlogic(list<Testing__c> testingrecords) // masala
    {
        for(Testing__c test: testingrecords)
        {
            if(test.OS_Type__c == 'apple mouse')
            {
                test.country__c = 'USA'; 
            }
        }
    }
    
    public static void beforeupdatelogic(list<Testing__c> testingrecords) //salt
    {
        
    }
        
    public static void afterinsertlogic(list<Testing__c> testingrecords)//chilli powder
    {
        
    }   
    public static void afterupdatelogic(list<Testing__c> testingrecords) // garlic paste
    {
        
    }
}