mdapipkg/unpackaged/objects/Testing__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OS_Type__c</fullName>
        <label>computer parts</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Windows</fullName>
                </value>
                <value>
                    <fullName>IOS</fullName>
                </value>
                <value>
                    <fullName>LINUX</fullName>
                </value>
                <value>
                    <fullName>apple mouse</fullName>
                </value>
                <value>
                    <fullName>windows harddisk</fullName>
                </value>
                <value>
                    <fullName>apple mointors</fullName>
                </value>
                <value>
                    <fullName>apple headset</fullName>
                </value>
                <value>
                    <fullName>windows keyboard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Testing</label>
    <nameField>
        <label>Testing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Testings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestingTrigger_Test.cls
@isTest
public class TestingTrigger_Test 
{
    //1) create dummy data .. 
    //2) send those data to the method
    //3) check you get what you expected.. 
    
    @testSetup static void testmethoh()
    {
        Testing__c dummydata  = new Testing__c();
        dummydata.Name ='testing';
        dummydata.Country__c ='testing';
		insert dummydata;        
    }
    
    @IsTest static void testRecordSession() {
        list<Testing__c> testingCreate = [Select id, name, country__c,os_type__c from testing__c where name='testing'];
        Test.startTest();
        Testingtrigger_handler.beforeinsertlogic(testingCreate);
        Testingtrigger_handler.afterinsertlogic(testingCreate);   
        Testingtrigger_handler.afterupdatelogic(testingCreate);
        Testingtrigger_handler.beforeupdatelogic(testingCreate);


        Test.stopTest();

    }
}