mdapipkg/unpackaged/objects/XMLInput__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalType__c</fullName>
        <label>ApprovalType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQQuoteId__c</fullName>
        <label>CPQQuoteId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpediteIncluded__c</fullName>
        <label>ExpediteIncluded</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <label>OpportunityId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteType__c</fullName>
        <label>QuoteType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFAQuoteId__c</fullName>
        <label>SFAQuoteId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <label>SubmittedBy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>XMLInput</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>XMLInput Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>XMLInputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/ClsXMLProcess.cls
public class ClsXMLProcess{
    public void ClsXMLProcessMethod(MyUserDefinedClassXML myCls){
        XMLInput__c objxml = new XMLInput__c();
        objxml.OpportunityId__c = myCls.OpportunityId;
        objxml.SFAQuoteId__c = myCls.SFAQuoteId;
        objxml.CPQQuoteId__c = myCls.CPQQuoteId;
        objxml.QuoteType__c = myCls.QuoteType;
        objxml.ApprovalType__c = myCls.ApprovalType;
        objxml.ExpediteIncluded__c = myCls.ExpediteIncluded;
        objxml.SubmittedBy__c = myCls.SubmittedBy;
        insert objxml;
                    
    }
}